import type { AlgorithmDefinition } from "../model/algorithm-trace";
import {
  buildAnagramTrace,
  buildDuplicateTrace,
  buildGroupAnagramsTrace,
  buildHashTwoSumTrace,
} from "../model/hash-traces";

export const hashDefinitions = {
  algo4: {
    pattern: "Hash Map · поиск дополнения",
    invariant:
      "Map хранит индексы только прошлых элементов: одно число нельзя использовать дважды.",
    complexity: "O(n) время · O(n) память",
    inputKind: "array",
    parameter: "target",
    build: buildHashTwoSumTrace,
    examples: [
      {
        id: "task-1",
        label: "Пример 1: [2, 7, 11, 15], target = 9",
        input: "2, 7, 11, 15",
        parameter: "9",
        isTask: true,
      },
      {
        id: "task-2",
        label: "Пример 2: [3, 2, 4], target = 6",
        input: "3, 2, 4",
        parameter: "6",
        isTask: true,
      },
      {
        id: "task-3",
        label: "Пример 3: [3, 3], target = 6",
        input: "3, 3",
        parameter: "6",
        isTask: true,
      },
      { id: "none", label: "Пары нет: [1, 2, 4], target = 8", input: "1, 2, 4", parameter: "8" },
      { id: "empty", label: "Пустой массив", input: "[]", parameter: "0" },
    ],
  },
  algo6: {
    pattern: "Hash Set · ранний выход",
    invariant: "Set хранит уникальные просмотренные числа. Повтор завершает поиск.",
    complexity: "O(n) время · O(n) память",
    inputKind: "array",
    build: buildDuplicateTrace,
    examples: [
      {
        id: "task-1",
        label: "Пример 1: [1, 2, 3, 1] (true)",
        input: "1, 2, 3, 1",
        isTask: true,
      },
      {
        id: "task-2",
        label: "Пример 2: [1, 2, 3, 4] (false)",
        input: "1, 2, 3, 4",
        isTask: true,
      },
      {
        id: "task-3",
        label: "Пример 3: [1, 1, 1, 3, 3, 4, 3, 2, 4, 2] (true)",
        input: "1, 1, 1, 3, 3, 4, 3, 2, 4, 2",
        isTask: true,
      },
      { id: "zero", label: "Нули: [0, 0]", input: "0, 0" },
      { id: "empty", label: "Пустой массив", input: "[]" },
    ],
  },
  algo5: {
    pattern: "Hash Map · счётчик частот",
    invariant: "Сначала считаем символы s, затем расходуем частоты символами t.",
    complexity: "O(n + m) время · O(Σ) память",
    inputKind: "text",
    parameter: "t",
    inputLabel: "Строка s",
    inputHint: "s и t: до 32 символов ASCII. Регистр и пробелы учитываются.",
    build: buildAnagramTrace,
    examples: [
      {
        id: "task-1",
        label: 'Пример 1: "anagram", "nagaram" (true)',
        input: "anagram",
        parameter: "nagaram",
        isTask: true,
      },
      {
        id: "task-2",
        label: 'Пример 2: "rat", "car" (false)',
        input: "rat",
        parameter: "car",
        isTask: true,
      },
      {
        id: "task-3",
        label: 'Пример 3: "listen", "silent" (true)',
        input: "listen",
        parameter: "silent",
        isTask: true,
      },
      { id: "count", label: 'Разные частоты: "aab", "abb"', input: "aab", parameter: "abb" },
      { id: "length", label: 'Разные длины: "ab", "a"', input: "ab", parameter: "a" },
      { id: "empty", label: "Пустые строки", input: "", parameter: "" },
    ],
  },
  algo7: {
    pattern: "Hash Map · группировка по ключу",
    invariant: "Отсортированные символы — общий ключ всех анаграмм в группе.",
    complexity: "O(n · m log m) время · O(n · m) память",
    inputKind: "words",
    inputLabel: "Массив строк",
    inputHint: "JSON: до 16 строк ASCII, до 8 символов в каждой. Регистр учитывается.",
    build: buildGroupAnagramsTrace,
    examples: [
      {
        id: "task-1",
        label: 'Пример 1: ["eat", "tea", "tan", "ate", "nat", "bat"]',
        input: '["eat", "tea", "tan", "ate", "nat", "bat"]',
        isTask: true,
      },
      {
        id: "task-2",
        label: 'Пример 2: [""]',
        input: '[""]',
        isTask: true,
      },
      {
        id: "task-3",
        label: 'Пример 3: ["a"]',
        input: '["a"]',
        isTask: true,
      },
      { id: "same", label: 'Повторы: ["", "a", "", "a"]', input: '["", "a", "", "a"]' },
      { id: "empty", label: "Пустой массив", input: "[]" },
    ],
  },
} satisfies Record<string, AlgorithmDefinition>;
