import type { AlgorithmDefinition } from "../model/algorithmTrace";
import { buildDisappearedTrace } from "../model/indexMarkTraces";
import {
  buildAnagramTrace,
  buildDuplicateTrace,
  buildGroupAnagramsTrace,
  buildHashTwoSumTrace,
} from "../model/hashTraces";

export const hashDefinitions = {
  algo4: {
    pattern: "Hash Map · поиск дополнения",
    invariant:
      "Map хранит индексы только прошлых элементов: одно число нельзя использовать дважды.",
    complexity: "O(n) время · O(n) память",
    inputKind: "array",
    parameter: "target",
    build: buildHashTwoSumTrace,
    examples: [
      {
        id: "task-1",
        label: "Пример 1: [5, 12, 3, 8], target = 11",
        input: "5, 12, 3, 8",
        parameter: "11",
        isTask: true,
      },
      {
        id: "task-2",
        label: "Пример 2: [4, -1, 7, 10], target = 3",
        input: "4, -1, 7, 10",
        parameter: "3",
        isTask: true,
      },
      {
        id: "task-3",
        label: "Пример 3: [6, 6, 1], target = 12",
        input: "6, 6, 1",
        parameter: "12",
        isTask: true,
      },
      { id: "none", label: "Пары нет: [1, 2, 4], target = 8", input: "1, 2, 4", parameter: "8" },
      { id: "empty", label: "Пустой массив", input: "[]", parameter: "0" },
    ],
  },
  algo6: {
    pattern: "Hash Set · ранний выход",
    invariant: "Set хранит уникальные просмотренные числа. Повтор завершает поиск.",
    complexity: "O(n) время · O(n) память",
    inputKind: "array",
    build: buildDuplicateTrace,
    examples: [
      { id: "task-1", label: "Пример 1: [7, 3, 9, 3] (true)", input: "7, 3, 9, 3", isTask: true },
      { id: "task-2", label: "Пример 2: [10, 20, 30] (false)", input: "10, 20, 30", isTask: true },
      { id: "task-3", label: "Пример 3: [5, 5] (true)", input: "5, 5", isTask: true },
      { id: "zero", label: "Нули: [0, 0]", input: "0, 0" },
      { id: "empty", label: "Пустой массив", input: "[]" },
    ],
  },
  algo5: {
    pattern: "Hash Map · счётчик частот",
    invariant: "Сначала считаем символы s, затем расходуем частоты символами t.",
    complexity: "O(n + m) время · O(Σ) память",
    inputKind: "text",
    parameter: "t",
    inputLabel: "Строка s",
    inputHint: "s и t: до 32 символов ASCII. Регистр и пробелы учитываются.",
    build: buildAnagramTrace,
    examples: [
      {
        id: "task-1",
        label: 'Пример 1: "dusty", "study" (true)',
        input: "dusty",
        parameter: "study",
        isTask: true,
      },
      {
        id: "task-2",
        label: 'Пример 2: "night", "thing" (true)',
        input: "night",
        parameter: "thing",
        isTask: true,
      },
      {
        id: "task-3",
        label: 'Пример 3: "hello", "world" (false)',
        input: "hello",
        parameter: "world",
        isTask: true,
      },
      {
        id: "task-4",
        label: 'Пример 4: "aab", "abb" (false)',
        input: "aab",
        parameter: "abb",
        isTask: true,
      },
      { id: "count", label: 'Разные частоты: "aab", "abb"', input: "aab", parameter: "abb" },
      { id: "length", label: 'Разные длины: "ab", "a"', input: "ab", parameter: "a" },
      { id: "empty", label: "Пустые строки", input: "", parameter: "" },
    ],
  },
  algo45: {
    pattern: "Hash Map · индекс как ключ",
    invariant:
      "Число x указывает на ячейку x − 1. Отрицательный знак в ячейке — «число уже встречалось». Положительные ячейки — пропущенные числа.",
    complexity: "O(n) время · O(1) память",
    inputKind: "indexed",
    inputLabel: "nums — n чисел от 1 до n",
    inputHint: "n чисел, каждое от 1 до n (n от 1 до 12). Массив меняется на месте.",
    build: buildDisappearedTrace,
    examples: [
      { id: "task-1", label: "Пример 1: [3, 1, 3, 5, 1]", input: "3, 1, 3, 5, 1", isTask: true },
      { id: "task-2", label: "Пример 2: [2, 2]", input: "2, 2", isTask: true },
      {
        id: "task-3",
        label: "Пример 3: [1, 4, 2, 3] (нет пропусков)",
        input: "1, 4, 2, 3",
        isTask: true,
      },
      { id: "task-4", label: "Пример 4: [5, 5, 5, 5, 5]", input: "5, 5, 5, 5, 5", isTask: true },
      { id: "repeat", label: "Один повтор: [3, 3, 3]", input: "3, 3, 3" },
    ],
  },
  algo7: {
    pattern: "Hash Map · группировка по ключу",
    invariant: "Отсортированные символы — общий ключ всех анаграмм в группе.",
    complexity: "O(n · m log m) время · O(n · m) память",
    inputKind: "words",
    inputLabel: "Массив строк",
    inputHint: "JSON: до 16 строк ASCII, до 8 символов в каждой. Регистр учитывается.",
    build: buildGroupAnagramsTrace,
    examples: [
      {
        id: "task-1",
        label: 'Пример 1: ["stop", "pots", "melon", "tops", "lemon", "pear"]',
        input: '["stop", "pots", "melon", "tops", "lemon", "pear"]',
        isTask: true,
      },
      {
        id: "task-2",
        label: 'Пример 2: ["abc", "", "cba", ""]',
        input: '["abc", "", "cba", ""]',
        isTask: true,
      },
      { id: "task-3", label: 'Пример 3: ["x"]', input: '["x"]', isTask: true },
      { id: "same", label: 'Повторы: ["", "a", "", "a"]', input: '["", "a", "", "a"]' },
      { id: "empty", label: "Пустой массив", input: "[]" },
    ],
  },
} satisfies Record<string, AlgorithmDefinition>;
