import type { AlgorithmDefinition } from "../model/algorithmTrace";
import {
  buildBinarySearchTrace,
  buildFirstBadTrace,
  buildRotatedSearchTrace,
  buildSearchInsertTrace,
} from "../model/searchTraces";

export const searchDefinitions = {
  algo14: {
    pattern: "Binary Search · точное совпадение",
    invariant:
      "Искомое число может находиться только в [left, right]. Каждый шаг исключает половину.",
    complexity: "O(log n) время · O(1) память",
    inputKind: "sorted",
    parameter: "target",
    build: buildBinarySearchTrace,
    examples: [
      {
        id: "task-1",
        label: "Пример 1: [-7, -2, 0, 4, 11, 19], target = 11",
        input: "-7, -2, 0, 4, 11, 19",
        parameter: "11",
        isTask: true,
      },
      {
        id: "task-2",
        label: "Пример 2: [-7, -2, 0, 4, 11, 19], target = 5",
        input: "-7, -2, 0, 4, 11, 19",
        parameter: "5",
        isTask: true,
      },
      {
        id: "task-3",
        label: "Пример 3: [8], target = 8",
        input: "8",
        parameter: "8",
        isTask: true,
      },
      { id: "empty", label: "Пустой массив", input: "[]", parameter: "0" },
    ],
  },
  algo15: {
    pattern: "Binary Search · позиция вставки",
    invariant: "При пустом диапазоне left указывает на позицию, сохраняющую порядок массива.",
    complexity: "O(log n) время · O(1) память",
    inputKind: "sorted",
    parameter: "target",
    build: buildSearchInsertTrace,
    examples: [
      {
        id: "task-1",
        label: "Пример 1: [10, 20, 30, 40], target = 30",
        input: "10, 20, 30, 40",
        parameter: "30",
        isTask: true,
      },
      {
        id: "task-2",
        label: "Пример 2: [10, 20, 30, 40], target = 25",
        input: "10, 20, 30, 40",
        parameter: "25",
        isTask: true,
      },
      {
        id: "task-3",
        label: "Пример 3: [10, 20, 30, 40], target = 5",
        input: "10, 20, 30, 40",
        parameter: "5",
        isTask: true,
      },
      {
        id: "task-4",
        label: "Пример 4: [10, 20, 30, 40], target = 50",
        input: "10, 20, 30, 40",
        parameter: "50",
        isTask: true,
      },
      { id: "empty", label: "Пустой массив", input: "[]", parameter: "0" },
    ],
  },
  algo16: {
    pattern: "Binary Search · монотонная граница",
    invariant: "Первая плохая версия остаётся в [left, right]. Плохую середину не исключаем.",
    complexity: "O(log n) вызовов API · O(1) память",
    inputKind: "versions",
    parameter: "firstBad",
    inputLabel: "Число версий n",
    inputHint: "От 1 до 16 версий. firstBad задаёт первую плохую версию (1…n). Индексы сцены с 0.",
    build: buildFirstBadTrace,
    examples: [
      {
        id: "task-1",
        label: "Пример 1: n = 10, firstBad = 6",
        input: "10",
        parameter: "6",
        isTask: true,
      },
      {
        id: "task-2",
        label: "Пример 2: n = 3, firstBad = 1",
        input: "3",
        parameter: "1",
        isTask: true,
      },
      { id: "basic", label: "Граница внутри (n = 8, bad = 4)", input: "8", parameter: "4" },
      { id: "last", label: "Только последняя (n = 5, bad = 5)", input: "5", parameter: "5" },
    ],
  },
  algo17: {
    pattern: "Binary Search · повёрнутый массив",
    invariant: "Одна из половин отсортирована. Проверяем, входит ли target в её границы.",
    complexity: "O(log n) время · O(1) память",
    inputKind: "rotated",
    parameter: "target",
    inputHint:
      "До 16 уникальных целых чисел: отсортированный массив с возможным циклическим сдвигом.",
    build: buildRotatedSearchTrace,
    examples: [
      {
        id: "task-1",
        label: "Пример 1: [30, 40, 50, 10, 20], target = 10",
        input: "30, 40, 50, 10, 20",
        parameter: "10",
        isTask: true,
      },
      {
        id: "task-2",
        label: "Пример 2: [30, 40, 50, 10, 20], target = 35",
        input: "30, 40, 50, 10, 20",
        parameter: "35",
        isTask: true,
      },
      {
        id: "task-3",
        label: "Пример 3: [6, 7, 1, 2, 3, 4, 5], target = 7",
        input: "6, 7, 1, 2, 3, 4, 5",
        parameter: "7",
        isTask: true,
      },
      {
        id: "task-4",
        label: "Пример 4: [2], target = 2",
        input: "2",
        parameter: "2",
        isTask: true,
      },
      {
        id: "right",
        label: "Правая половина упорядочена (target = 7)",
        input: "6, 7, 0, 1, 2, 4, 5",
        parameter: "7",
      },
      { id: "empty", label: "Пустой массив", input: "[]", parameter: "0" },
    ],
  },
} satisfies Record<string, AlgorithmDefinition>;
