/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeRouteImport } from './routes/home'
import { Route as AlgorithmsIndexRouteImport } from './routes/algorithms/index'
import { Route as JavascriptIndexRouteImport } from './routes/javascript/index'
import { Route as JavascriptTaskIdRouteImport } from './routes/javascript/$taskId'
import { Route as ReactIndexRouteImport } from './routes/react/index'
import { Route as ReactTaskIdRouteImport } from './routes/react/$taskId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgorithmsIndexRoute = AlgorithmsIndexRouteImport.update({
  id: '/algorithms/',
  path: '/algorithms/',
  getParentRoute: () => rootRouteImport,
} as any)
const JavascriptIndexRoute = JavascriptIndexRouteImport.update({
  id: '/javascript/',
  path: '/javascript/',
  getParentRoute: () => rootRouteImport,
} as any)
const JavascriptTaskIdRoute = JavascriptTaskIdRouteImport.update({
  id: '/javascript/$taskId',
  path: '/javascript/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReactIndexRoute = ReactIndexRouteImport.update({
  id: '/react/',
  path: '/react/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReactTaskIdRoute = ReactTaskIdRouteImport.update({
  id: '/react/$taskId',
  path: '/react/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/javascript/$taskId': typeof JavascriptTaskIdRoute
  '/react/$taskId': typeof ReactTaskIdRoute
  '/algorithms/': typeof AlgorithmsIndexRoute
  '/javascript/': typeof JavascriptIndexRoute
  '/react/': typeof ReactIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/javascript/$taskId': typeof JavascriptTaskIdRoute
  '/react/$taskId': typeof ReactTaskIdRoute
  '/algorithms': typeof AlgorithmsIndexRoute
  '/javascript': typeof JavascriptIndexRoute
  '/react': typeof ReactIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/javascript/$taskId': typeof JavascriptTaskIdRoute
  '/react/$taskId': typeof ReactTaskIdRoute
  '/algorithms/': typeof AlgorithmsIndexRoute
  '/javascript/': typeof JavascriptIndexRoute
  '/react/': typeof ReactIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/javascript/$taskId'
    | '/react/$taskId'
    | '/algorithms/'
    | '/javascript/'
    | '/react/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/javascript/$taskId'
    | '/react/$taskId'
    | '/algorithms'
    | '/javascript'
    | '/react'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/javascript/$taskId'
    | '/react/$taskId'
    | '/algorithms/'
    | '/javascript/'
    | '/react/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  JavascriptTaskIdRoute: typeof JavascriptTaskIdRoute
  ReactTaskIdRoute: typeof ReactTaskIdRoute
  AlgorithmsIndexRoute: typeof AlgorithmsIndexRoute
  JavascriptIndexRoute: typeof JavascriptIndexRoute
  ReactIndexRoute: typeof ReactIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algorithms/': {
      id: '/algorithms/'
      path: '/algorithms'
      fullPath: '/algorithms/'
      preLoaderRoute: typeof AlgorithmsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/javascript/': {
      id: '/javascript/'
      path: '/javascript'
      fullPath: '/javascript/'
      preLoaderRoute: typeof JavascriptIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/javascript/$taskId': {
      id: '/javascript/$taskId'
      path: '/javascript/$taskId'
      fullPath: '/javascript/$taskId'
      preLoaderRoute: typeof JavascriptTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/react/': {
      id: '/react/'
      path: '/react'
      fullPath: '/react/'
      preLoaderRoute: typeof ReactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/react/$taskId': {
      id: '/react/$taskId'
      path: '/react/$taskId'
      fullPath: '/react/$taskId'
      preLoaderRoute: typeof ReactTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  JavascriptTaskIdRoute: JavascriptTaskIdRoute,
  ReactTaskIdRoute: ReactTaskIdRoute,
  AlgorithmsIndexRoute: AlgorithmsIndexRoute,
  JavascriptIndexRoute: JavascriptIndexRoute,
  ReactIndexRoute: ReactIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
