/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeRouteImport } from './routes/home'
import { Route as AlgorithmsIndexRouteImport } from './routes/algorithms/index'
import { Route as AlgorithmsTaskIdRouteImport } from './routes/algorithms/$taskId'
import { Route as JavascriptIndexRouteImport } from './routes/javascript/index'
import { Route as JavascriptTaskIdRouteImport } from './routes/javascript/$taskId'
import { Route as OpenIndexRouteImport } from './routes/open/index'
import { Route as OpenTaskIdRouteImport } from './routes/open/$taskId'
import { Route as ReactIndexRouteImport } from './routes/react/index'
import { Route as ReactTaskIdRouteImport } from './routes/react/$taskId'
import { Route as OpenAlgorithmsTaskIdRouteImport } from './routes/open/algorithms/$taskId'
import { Route as OpenJavascriptTaskIdRouteImport } from './routes/open/javascript/$taskId'
import { Route as OpenReactTaskIdRouteImport } from './routes/open/react/$taskId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgorithmsIndexRoute = AlgorithmsIndexRouteImport.update({
  id: '/algorithms/',
  path: '/algorithms/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgorithmsTaskIdRoute = AlgorithmsTaskIdRouteImport.update({
  id: '/algorithms/$taskId',
  path: '/algorithms/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const JavascriptIndexRoute = JavascriptIndexRouteImport.update({
  id: '/javascript/',
  path: '/javascript/',
  getParentRoute: () => rootRouteImport,
} as any)
const JavascriptTaskIdRoute = JavascriptTaskIdRouteImport.update({
  id: '/javascript/$taskId',
  path: '/javascript/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenIndexRoute = OpenIndexRouteImport.update({
  id: '/open/',
  path: '/open/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenTaskIdRoute = OpenTaskIdRouteImport.update({
  id: '/open/$taskId',
  path: '/open/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReactIndexRoute = ReactIndexRouteImport.update({
  id: '/react/',
  path: '/react/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReactTaskIdRoute = ReactTaskIdRouteImport.update({
  id: '/react/$taskId',
  path: '/react/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenAlgorithmsTaskIdRoute = OpenAlgorithmsTaskIdRouteImport.update({
  id: '/open/algorithms/$taskId',
  path: '/open/algorithms/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenJavascriptTaskIdRoute = OpenJavascriptTaskIdRouteImport.update({
  id: '/open/javascript/$taskId',
  path: '/open/javascript/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenReactTaskIdRoute = OpenReactTaskIdRouteImport.update({
  id: '/open/react/$taskId',
  path: '/open/react/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/algorithms/$taskId': typeof AlgorithmsTaskIdRoute
  '/javascript/$taskId': typeof JavascriptTaskIdRoute
  '/open/$taskId': typeof OpenTaskIdRoute
  '/react/$taskId': typeof ReactTaskIdRoute
  '/algorithms/': typeof AlgorithmsIndexRoute
  '/javascript/': typeof JavascriptIndexRoute
  '/open/': typeof OpenIndexRoute
  '/react/': typeof ReactIndexRoute
  '/open/algorithms/$taskId': typeof OpenAlgorithmsTaskIdRoute
  '/open/javascript/$taskId': typeof OpenJavascriptTaskIdRoute
  '/open/react/$taskId': typeof OpenReactTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/algorithms/$taskId': typeof AlgorithmsTaskIdRoute
  '/javascript/$taskId': typeof JavascriptTaskIdRoute
  '/open/$taskId': typeof OpenTaskIdRoute
  '/react/$taskId': typeof ReactTaskIdRoute
  '/algorithms': typeof AlgorithmsIndexRoute
  '/javascript': typeof JavascriptIndexRoute
  '/open': typeof OpenIndexRoute
  '/react': typeof ReactIndexRoute
  '/open/algorithms/$taskId': typeof OpenAlgorithmsTaskIdRoute
  '/open/javascript/$taskId': typeof OpenJavascriptTaskIdRoute
  '/open/react/$taskId': typeof OpenReactTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/algorithms/$taskId': typeof AlgorithmsTaskIdRoute
  '/javascript/$taskId': typeof JavascriptTaskIdRoute
  '/open/$taskId': typeof OpenTaskIdRoute
  '/react/$taskId': typeof ReactTaskIdRoute
  '/algorithms/': typeof AlgorithmsIndexRoute
  '/javascript/': typeof JavascriptIndexRoute
  '/open/': typeof OpenIndexRoute
  '/react/': typeof ReactIndexRoute
  '/open/algorithms/$taskId': typeof OpenAlgorithmsTaskIdRoute
  '/open/javascript/$taskId': typeof OpenJavascriptTaskIdRoute
  '/open/react/$taskId': typeof OpenReactTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/algorithms/$taskId'
    | '/javascript/$taskId'
    | '/open/$taskId'
    | '/react/$taskId'
    | '/algorithms/'
    | '/javascript/'
    | '/open/'
    | '/react/'
    | '/open/algorithms/$taskId'
    | '/open/javascript/$taskId'
    | '/open/react/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/algorithms/$taskId'
    | '/javascript/$taskId'
    | '/open/$taskId'
    | '/react/$taskId'
    | '/algorithms'
    | '/javascript'
    | '/open'
    | '/react'
    | '/open/algorithms/$taskId'
    | '/open/javascript/$taskId'
    | '/open/react/$taskId'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/algorithms/$taskId'
    | '/javascript/$taskId'
    | '/open/$taskId'
    | '/react/$taskId'
    | '/algorithms/'
    | '/javascript/'
    | '/open/'
    | '/react/'
    | '/open/algorithms/$taskId'
    | '/open/javascript/$taskId'
    | '/open/react/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  AlgorithmsTaskIdRoute: typeof AlgorithmsTaskIdRoute
  JavascriptTaskIdRoute: typeof JavascriptTaskIdRoute
  OpenTaskIdRoute: typeof OpenTaskIdRoute
  ReactTaskIdRoute: typeof ReactTaskIdRoute
  AlgorithmsIndexRoute: typeof AlgorithmsIndexRoute
  JavascriptIndexRoute: typeof JavascriptIndexRoute
  OpenIndexRoute: typeof OpenIndexRoute
  ReactIndexRoute: typeof ReactIndexRoute
  OpenAlgorithmsTaskIdRoute: typeof OpenAlgorithmsTaskIdRoute
  OpenJavascriptTaskIdRoute: typeof OpenJavascriptTaskIdRoute
  OpenReactTaskIdRoute: typeof OpenReactTaskIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algorithms/': {
      id: '/algorithms/'
      path: '/algorithms'
      fullPath: '/algorithms/'
      preLoaderRoute: typeof AlgorithmsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algorithms/$taskId': {
      id: '/algorithms/$taskId'
      path: '/algorithms/$taskId'
      fullPath: '/algorithms/$taskId'
      preLoaderRoute: typeof AlgorithmsTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/javascript/': {
      id: '/javascript/'
      path: '/javascript'
      fullPath: '/javascript/'
      preLoaderRoute: typeof JavascriptIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/javascript/$taskId': {
      id: '/javascript/$taskId'
      path: '/javascript/$taskId'
      fullPath: '/javascript/$taskId'
      preLoaderRoute: typeof JavascriptTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open/': {
      id: '/open/'
      path: '/open'
      fullPath: '/open/'
      preLoaderRoute: typeof OpenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open/$taskId': {
      id: '/open/$taskId'
      path: '/open/$taskId'
      fullPath: '/open/$taskId'
      preLoaderRoute: typeof OpenTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/react/': {
      id: '/react/'
      path: '/react'
      fullPath: '/react/'
      preLoaderRoute: typeof ReactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/react/$taskId': {
      id: '/react/$taskId'
      path: '/react/$taskId'
      fullPath: '/react/$taskId'
      preLoaderRoute: typeof ReactTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open/algorithms/$taskId': {
      id: '/open/algorithms/$taskId'
      path: '/open/algorithms/$taskId'
      fullPath: '/open/algorithms/$taskId'
      preLoaderRoute: typeof OpenAlgorithmsTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open/javascript/$taskId': {
      id: '/open/javascript/$taskId'
      path: '/open/javascript/$taskId'
      fullPath: '/open/javascript/$taskId'
      preLoaderRoute: typeof OpenJavascriptTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open/react/$taskId': {
      id: '/open/react/$taskId'
      path: '/open/react/$taskId'
      fullPath: '/open/react/$taskId'
      preLoaderRoute: typeof OpenReactTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  AlgorithmsTaskIdRoute: AlgorithmsTaskIdRoute,
  JavascriptTaskIdRoute: JavascriptTaskIdRoute,
  OpenTaskIdRoute: OpenTaskIdRoute,
  ReactTaskIdRoute: ReactTaskIdRoute,
  AlgorithmsIndexRoute: AlgorithmsIndexRoute,
  JavascriptIndexRoute: JavascriptIndexRoute,
  OpenIndexRoute: OpenIndexRoute,
  ReactIndexRoute: ReactIndexRoute,
  OpenAlgorithmsTaskIdRoute: OpenAlgorithmsTaskIdRoute,
  OpenJavascriptTaskIdRoute: OpenJavascriptTaskIdRoute,
  OpenReactTaskIdRoute: OpenReactTaskIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
